#!/bin/sh
# .xmonad/session
# Script used by Fedora xmonad Xsession script to specify custom commands to
# run

# Turn off AccessX
[ -x /usr/bin/xkbset ] && /usr/bin/xkbset -a

if [ -x /usr/libexec/polkit-gnome-authentication-agent-1 ]; then
	/usr/libexec/polkit-gnome-authentication-agent-1 &
fi
if [ -x /usr/libexec/deja-dup/deja-dup-monitor ]; then
	/usr/libexec/deja-dup/deja-dup-monitor &
fi

xscreensaver -no-splash &
~/bin/wallpaper.sh &
trayer --edge top --align right --SetDockType true --SetPartialStrut true --height 16 --widthtype pixel --width 100 --tint 0x073642 --alpha 0 --transparent true &
nm-applet --sm-disable &
urxvt -ls &
